### PR TITLE
In laravel 7.x ramsey/uuid 4.0.1 is installed by default. To make it …

### PR DESCRIPTION
**Pull request by martinnaughton**
…compatible with laravel 7.x the database library should work with ramsey/uuid 4.0.1 aswell

### CODE REVIEW

**Comment by depsimon** [comment]
Hello @mirzap, could you please merge this PR?

This'll make laravel-postgis work with latest version of Laravel & uuid.


Thanks

**Comment by depsimon** [comment]
Thanks a lot :)

**Comment by gbuckingham89** [comment]
@mirzap It looks like this is merged - but can you take a new release please? 

Latest release in Packagist is 0.20 - which doesn't have the recent commits for Laravel ^7.0 and ramsey/uuid 4.0.1 support.

Thanks!

**Comment by BrekiTomasson** [comment]
Ping @mirzap - Many of us still waiting for a release that includes this change, as the 0.20 release is still the most recent.

**Pull request merged**
